apiVersion: v1
kind: Service
metadata:
  namespace: redis-cluster
  labels:
    app: deployment-redis
  name: svc-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    nodePort: 32666
  selector:
    app: deployment-redis
  type: NodePort